### ISSUE TITLE
Broken specs for Rdio::Server

### ISSUE THREAD

**Issue by radamant** [radamant/robut-rdio#11]
```
...............FF

Failures:

  1) Robut::Plugin::Rdio::Server should be able to tell HipChat what song is playing
     Failure/Error: last_response.should be_ok
       expected ok? to return true, got false
     # ./spec/server_spec.rb:19:in `block (2 levels) in <top (required)>'

  2) Robut::Plugin::Rdio::Server should degrade gracefully if a reply_callback has not been defined
     Failure/Error: last_response.should be_ok
       expected ok? to return true, got false
     # ./spec/server_spec.rb:26:in `block (2 levels) in <top (required)>'

Finished in 0.51483 seconds
17 examples, 2 failures
```

**Comment by burtlo** [comment]
Fix https://github.com/radamant/robut-rdio/commit/c7eac16295a2a8fa477fc1cfed86987b18c3db7c
