### ISSUE TITLE
Now Playing - Artists or Tracks with special characters will not be reported

### ISSUE THREAD

**Issue by burtlo** [radamant/robut-rdio#4]
`ArgumentError - invalid byte sequence in UTF-8:
    /Users/burtlo/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/uri/common.rb:230:in `gsub'
    /Users/burtlo/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/uri/common.rb:230:in `unescape'
    /Users/burtlo/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/uri/common.rb:531:in `unescape'
    /Users/burtlo/.rvm/gems/ruby-1.9.2-p290@robut-rdio/gems/robut-rdio-0.1.0/lib/server/server.rb:72:in `block in <class:Server>'
    /Users/burtlo/.rvm/gems/ruby-1.9.2-p290@robut-rdio/gems/sinatra-1.3.1/lib/sinatra/base.rb:1212:in `call'
    /Users/burtlo/.rvm/gems/ruby-1.9.2-p290@robut-rdio/gems/sinatra-1.3.1/lib/sinatra/base.rb:1212:in `block in compile!'
    /Users/burtlo/.rvm/gems/ruby-1.9.2-p290@robut-rdio/gems/sinatra-1.3.1/lib/sinatra/base.rb:772:in `[]'
    /Users/burtlo/.rvm/gems/ruby-1.9.2-p290@robut-rdio/gems/sinatra-1.3.1/lib/sinatra/base.rb:772:in `block (3 levels) in route!'
    /Users/burtlo/.rvm/gems/ruby-1.9.2-p290@robut-rdio/gems/sinatra-1.3.1/lib/sinatra/base.rb:788:in `route_eval'
    /Users/burtlo/.rvm/gems/ruby-1.9.2-p290@robut-rdio/gems/sinatra-1.3.1/lib/sinatra/base.rb:772:in `block (2 levels) in route!'
    /Users/burtlo/.rvm/gems/ruby-1.9.2-p290@robut-rdio/gems/sinatra-1.3.1/lib/sinatra/base.rb:821:in `block in process_route'
    /Users/burtlo/.rvm/gems/ruby-1.9.2-p290@robut-rdio/gems/sinatra-1.3.1/lib/sinatra/base.rb:819:in `catch'
    /Users/burtlo/.rvm/gems/ruby-1.9.2-p290@robut-rdio/gems/sinatra-1.3.1/lib/sinatra/base.rb:819:in `process_route'
    /Users/burtlo/.rvm/gems/ruby-1.9.2-p290@robut-rdio/gems/sinatra-1.3.1/lib/sinatra/base.rb:771:in `block in route!'
    /Users/burtlo/.rvm/gems/ruby-1.9.2-p290@robut-rdio/gems/sinatra-1.3.1/lib/sinatra/base.rb:770:in `each'
    /Users/burtlo/.rvm/gems/ruby-1.9.2-p290@robut-rdio/gems/sinatra-1.3.1/lib/sinatra/base.rb:770:in `route!'
    /Users/burtlo/.rvm/gems/ruby-1.9.2-p290@robut-rdio/gems/sinatra-1.3.1/lib/sinatra/base.rb:886:in `dispatch!'
    /Users/burtlo/.rvm/gems/ruby-1.9.2-p290@robut-rdio/gems/sinatra-1.3.1/lib/sinatra/base.rb:706:in `block in call!'
    /Users/burtlo/.rvm/gems/ruby-1.9.2-p290@robut-rdio/gems/sinatra-1.3.1/lib/sinatra/base.rb:871:in `block in invoke'
    /Users/burtlo/.rvm/gems/ruby-1.9.2-p290@robut-rdio/gems/sinatra-1.3.1/lib/sinatra/base.rb:871:in `catch'
    /Users/burtlo/.rvm/gems/ruby-1.9.2-p290@robut-rdio/gems/sinatra-1.3.1/lib/sinatra/base.rb:871:in `invoke'
    /Users/burtlo/.rvm/gems/ruby-1.9.2-p290@robut-rdio/gems/sinatra-1.3.1/lib/sinatra/base.rb:706:in `call!'
    /Users/burtlo/.rvm/gems/ruby-1.9.2-p290@robut-rdio/gems/sinatra-1.3.1/lib/sinatra/base.rb:692:in `call'
    /Users/burtlo/.rvm/gems/ruby-1.9.2-p290@robut-rdio/gems/rack-protection-1.1.4/lib/rack/protection/xss_header.rb:22:in `call'
    /Users/burtlo/.rvm/gems/ruby-1.9.2-p290@robut-rdio/gems/rack-protection-1.1.4/lib/rack/protection/path_traversal.rb:16:in `call'
    /Users/burtlo/.rvm/gems/ruby-1.9.2-p290@robut-rdio/gems/rack-protection-1.1.4/lib/rack/protection/json_csrf.rb:17:in `call'
    /Users/burtlo/.rvm/gems/ruby-1.9.2-p290@robut-rdio/gems/rack-protection-1.1.4/lib/rack/protection/base.rb:47:in `call'
    /Users/burtlo/.rvm/gems/ruby-1.9.2-p290@robut-rdio/gems/rack-protection-1.1.4/lib/rack/protection/xss_header.rb:22:in `call'
    /Users/burtlo/.rvm/gems/ruby-1.9.2-p290@robut-rdio/gems/rack-1.3.5/lib/rack/nulllogger.rb:9:in `call'
    /Users/burtlo/.rvm/gems/ruby-1.9.2-p290@robut-rdio/gems/rack-1.3.5/lib/rack/head.rb:9:in `call'
    /Users/burtlo/.rvm/gems/ruby-1.9.2-p290@robut-rdio/gems/sinatra-1.3.1/lib/sinatra/showexceptions.rb:21:in `call'
    /Users/burtlo/.rvm/gems/ruby-1.9.2-p290@robut-rdio/gems/sinatra-1.3.1/lib/sinatra/base.rb:1334:in `block in call'
    /Users/burtlo/.rvm/gems/ruby-1.9.2-p290@robut-rdio/gems/sinatra-1.3.1/lib/sinatra/base.rb:1403:in `synchronize'
    /Users/burtlo/.rvm/gems/ruby-1.9.2-p290@robut-rdio/gems/sinatra-1.3.1/lib/sinatra/base.rb:1334:in `call'
    /Users/burtlo/.rvm/gems/ruby-1.9.2-p290@robut-rdio/gems/thin-1.2.11/lib/thin/connection.rb:84:in `block in pre_process'
    /Users/burtlo/.rvm/gems/ruby-1.9.2-p290@robut-rdio/gems/thin-1.2.11/lib/thin/connection.rb:82:in `catch'
    /Users/burtlo/.rvm/gems/ruby-1.9.2-p290@robut-rdio/gems/thin-1.2.11/lib/thin/connection.rb:82:in `pre_process'
    /Users/burtlo/.rvm/gems/ruby-1.9.2-p290@robut-rdio/gems/eventmachine-0.12.10/lib/eventmachine.rb:1060:in `call'
    /Users/burtlo/.rvm/gems/ruby-1.9.2-p290@robut-rdio/gems/eventmachine-0.12.10/lib/eventmachine.rb:1060:in `block in spawn_threadpool'`
### Steps to Reproduce
- @dj play sigur ros

**Comment by burtlo** [comment]
Fixed with https://github.com/radamant/robut-rdio/commit/fc35fd97191db82f787f82dad8bb2217d7897a6f
